language: python
python:
  - "3.4"
cache:
  directories:
    - $HOME/.cache/pip
    - node_modules
env:
  global:
    - SAUCE_CONNECT=true
    - secure: L22k89oDjcsXggQUCNCHQPpVcRDybi/kiNJpjBMV+NbL/aZeCNBocbcaXe9XF9OhyJBiTwxpubo4DwjaidXVf14hHBppcuwrn+QBc2I7cOD5+oFf8IkemdXC9sCuich8fyL5+zBBEknh1MpiiBw5v5cW8qs9ok+N/oM85sEK3A4=
    - secure: V0Gv+NTYR0ODMUWW9/Fb8ZJC4aTo1pqsD7kxobp51kbe7p+Vn9Ntkt75GBXaw+3fJhU1Xp2029+/rvMTWv5GweJ3eMt2fEN2nwHPwm7MRabhFllzVvet5hXfLXZw+ZsLuWWXhDjEUXCESW2br3UeMDUPdxHTt/NCBEgIEWMmiR8=
  matrix:
    - "BROWSER='android:4.1:Linux:Android Emulator'"
    - "BROWSER='android:4.2:Linux:Android Emulator'"
    - "BROWSER='android:4.3:Linux:Android Emulator'"
    - "BROWSER='android:4.4:Linux:Android Emulator'"
    - "BROWSER='android:5.0:Linux:Android Emulator'"
addons:
  postgresql: "9.4"
  sauce_connect: true

before_install:
  - pip install selenium beautifulsoup4 py-dateutil pytz

before_script:
  - psql -c 'create database doko;' -U postgres
  - head -c 24 /dev/urandom > cookie_secret
  - nvm install stable
  - npm install npm -g
  - npm install
  - ./tests/python/selenium_webapp.py &>/dev/null &
  - sleep 2
  - node_modules/gulp/bin/gulp.js dev-build

script:
  - python -m unittest tests.python.test_selenium
