language: python
python:
  - "3.4"
cache: pip
env:
  global:
    - SAUCE_CONNECT=true
    - secure: L22k89oDjcsXggQUCNCHQPpVcRDybi/kiNJpjBMV+NbL/aZeCNBocbcaXe9XF9OhyJBiTwxpubo4DwjaidXVf14hHBppcuwrn+QBc2I7cOD5+oFf8IkemdXC9sCuich8fyL5+zBBEknh1MpiiBw5v5cW8qs9ok+N/oM85sEK3A4=
    - secure: V0Gv+NTYR0ODMUWW9/Fb8ZJC4aTo1pqsD7kxobp51kbe7p+Vn9Ntkt75GBXaw+3fJhU1Xp2029+/rvMTWv5GweJ3eMt2fEN2nwHPwm7MRabhFllzVvet5hXfLXZw+ZsLuWWXhDjEUXCESW2br3UeMDUPdxHTt/NCBEgIEWMmiR8=
  matrix:
    - "BROWSER='firefox::Linux'"
    - "BROWSER='firefox::OS X 10.6'"
    - "BROWSER='firefox::OS X 10.9'"
    - "BROWSER='firefox::OS X 10.10'"
    - "BROWSER='firefox::Windows XP'"
    - "BROWSER='firefox::Windows 7'"
    - "BROWSER='firefox::Windows 8'"
    - "BROWSER='firefox::Windows 8.1'"
    - "BROWSER='chrome::Linux'"
    - "BROWSER='chrome::OS X 10.6'"
    - "BROWSER='chrome::OS X 10.8'"
    - "BROWSER='chrome::OS X 10.9'"
    - "BROWSER='chrome::OS X 10.10'"
    - "BROWSER='chrome::Windows XP'"
    - "BROWSER='chrome::Windows 7'"
    - "BROWSER='chrome::Windows 8'"
    - "BROWSER='chrome::Windows 8.1'"
    - "BROWSER='android:4.0:Linux:Android Emulator'"
    - "BROWSER='android:4.1:Linux:Android Emulator'"
    - "BROWSER='android:4.2:Linux:Android Emulator'"
    - "BROWSER='android:4.3:Linux:Android Emulator'"
    - "BROWSER='android:4.4:Linux:Android Emulator'"
    - "BROWSER='android:5.0:Linux:Android Emulator'"
    - "BROWSER='iPhone:8.1:OS X 10.10:iPhone Simulator'"
    - "BROWSER='iPhone:8.1:OS X 10.10:iPad Simulator'"
    - "BROWSER='safari::OS X 10.10'"
    - "BROWSER='safari::Windows 7'"
    - "BROWSER='internet explorer:6.0:Windows XP'"
    - "BROWSER='internet explorer:7.0:Windows XP'"
    - "BROWSER='internet explorer:8.0:Windows XP'"
    - "BROWSER='internet explorer:8.0:Windows 7'"
    - "BROWSER='internet explorer:9.0:Windows 7'"
    - "BROWSER='internet explorer:10.0:Windows 7'"
    - "BROWSER='internet explorer:11.0:Windows 7'"
    - "BROWSER='internet explorer::Windows 8'"
    - "BROWSER='internet explorer::Windows 8.1'"
addons:
  postgresql: "9.4"
  sauce_connect: true

install:
  - pip install -r requirements.txt
  - pip install selenium

before_script:
  - psql -c 'create database doko;' -U postgres
  - head -c 24 /dev/urandom > cookie_secret
  - ./webapp.py --port=9999 --debug=True --https=False --persona_verification_url=http://localhost:9999/debug/persona_verify &

script:
  - python -m unittest tests.test_selenium
