language: python
python:
  - "3.4"
cache:
  directories:
    - $HOME/.cache/pip
    - node_modules
env:
  global:
    - SAUCE_CONNECT=true
    - secure: IrFp6lAB4leV7IOlnpaW2C4QVPFg9oHJFyXQQy0rhSkM118ezGNyMCCDOM2IvlIEtwn6vtfqZIgWwZzqW8mXl+uWmYe7u50lBWkOBwR5NdVKF/PBfXi/82iJ36PaInE0kMlY+6vKUJVNIftnfKs0J9uFIQoWPxFYVXahk6FkM2Q=
    - secure: YNjBjniFtaGMPI2pQXUQEvrvOE0QWJmadljvmjZxE2A1aIPNwFGp/3KVl7cn+KRJadCqAuzRiFB4ZyFY1qbqkkx0vSG4FBqTDZAHwhGThxMkiYqx6dyo+GTDcy+MYPzdzMUv12vQ1juGdn89+4h0rke1tepLFMKyXW0Y3qi/IN4=
  matrix:
    - "BROWSER='firefox::Linux'"
    - "BROWSER='firefox::OS X 10.11'"
    - "BROWSER='firefox::Windows XP'"
    - "BROWSER='firefox::Windows 7'"
    - "BROWSER='firefox::Windows 8'"
    - "BROWSER='firefox::Windows 8.1'"
    - "BROWSER='firefox::Windows 10'"
    - "BROWSER='chrome::Linux'"
    - "BROWSER='chrome::OS X 10.11'"
    - "BROWSER='chrome::Windows XP'"
    - "BROWSER='chrome::Windows 7'"
    - "BROWSER='chrome::Windows 8'"
    - "BROWSER='chrome::Windows 8.1'"
    - "BROWSER='chrome::Windows 10'"
    - "BROWSER='android:4.0:Linux:Android Emulator'"
    - "BROWSER='android:4.1:Linux:Android Emulator'"
    - "BROWSER='android:4.2:Linux:Android Emulator'"
    - "BROWSER='android:4.3:Linux:Android Emulator'"
    - "BROWSER='android:4.4:Linux:Android Emulator'"
    - "BROWSER='android:5.0:Linux:Android Emulator'"
    - "BROWSER='iPhone:8.1:OS X 10.10:iPhone Simulator'"
    - "BROWSER='iPhone:8.1:OS X 10.10:iPad Simulator'"
    - "BROWSER='safari::OS X 10.11'"
    - "BROWSER='safari::Windows 7'"
    - "BROWSER='internet explorer:6.0:Windows XP'"
    - "BROWSER='internet explorer:7.0:Windows XP'"
    - "BROWSER='internet explorer:8.0:Windows XP'"
    - "BROWSER='internet explorer:8.0:Windows 7'"
    - "BROWSER='internet explorer:9.0:Windows 7'"
    - "BROWSER='internet explorer:10.0:Windows 7'"
    - "BROWSER='internet explorer:11.0:Windows 7'"
    - "BROWSER='internet explorer::Windows 8'"
    - "BROWSER='internet explorer::Windows 8.1'"
    - "BROWSER='internet explorer::Windows 10'"
addons:
  postgresql: "9.4"
  sauce_connect: true

before_install:
  - pip install selenium beautifulsoup4 py-dateutil

before_script:
  - psql -c 'create database doko;' -U postgres
  - head -c 24 /dev/urandom > cookie_secret
  - nvm install stable
  - npm install
  - ./tests/python/selenium_webapp.py &>/dev/null &
  - sleep 2
  - node_modules/gulp/bin/gulp.js dev-build

script:
  - python -m unittest tests.python.test_selenium
